version: "3.7"

services:
  database_ecommerce:
    image: postgres
    container_name: database_ecommerce
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local